name: Create MacOS x64 executable
run-name: Building MacOS x64 executable 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.13
      - run: uv sync
      - run: pip install pyinstaller
      - run: pyinstaller src/vinyl_goblin/__main__.py --onefile --name vinyl_goblin_macos_x64 --paths __pypackages__/3.13/lib --add-data src/vinyl_goblin/banner.txt:. --target-arch x86_64
      - uses: actions/upload-artifact@v4
        with:
          path: dist/*
      - name: Release MacOS x64 Executable
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/vinyl_goblin_macos_x64
          token: ${{ secrets.PUBLISH_RELEASE_TOKEN }}
