name: Create executable
run-name: Building executable 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: curl -sSL https://pdm-project.org/install-pdm.py | python3 -
      - run: pdm install
      - run: pdm export > src/requirements.txt
      - run: pwd
      - run: ls -la
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13'
          spec: 'src/build.spec'
          requirements: 'src/requirements.txt'
          upload_exe_with_name: 'vinylgoblin'
          options: --onefile, --name "Vinyl Goblin", --windowed, 
