name: Create executable
run-name: Building executable 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.13'
      - run: pdm config python.use_venv false
      - run: pdm install --dev
      - run: pdm export > src/requirements.txt
      - run: pyinstaller src/VinylGoblin
      # - name: Create Executable
      #   uses: sayyid5416/pyinstaller@v1
      #   with:
      #     python_ver: '3.13'
      #     spec: 'src/build.spec'
      #     requirements: 'src/requirements.txt'
      #     upload_exe_with_name: 'vinylgoblin'
      #     options: --onefile, --name "Vinyl Goblin", --windowed, 
