name: Create executable
run-name: Building executable 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.13'
      - run: pdm config python.use_venv false
      - run: pdm install
      - run: pdm export > requirements.txt
      - run: pip install pyinstaller
      - run: ls -la /home/runner/.local/share/pdm/venv/lib/python3.13/site-packages
      - run: pyinstaller src/vinyl_goblin/__main__.py --onefile --name vinyl_goblin --paths /home/runner/.local/share/pdm/venv/lib/python3.13/site-packages
      - uses: actions/upload-artifact@v4
        with:
          path: dist/*
